apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  containers:
  - name: web
    image: bmuschko/nodejs-read-config:1.0.0
    ports:
    - containerPort: 8080
    volumeMounts:
    - mountPath: "/usr/shared/app"
      name: vol
  initContainers:
  - name: configurer
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: "/usr/shared/app"
      name: vol
    command:
    - curl
    - "-O"
    - "https://raw.githubusercontent.com/bmuschko/ckad-crash-course/master/exercises/07-creating-init-container/app/config/config.json"
  volumes:
  - name: vol
    emptyDir: {}
